[package]
name = "alds"
version = "0.1.0"
edition = "2021"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }

# original crates
mod_int = { path = "crates/mod_int" }
union_find = { path = "crates/union_find" }

[workspace]
members = [
    "crates/mod_int",
    "crates/union_find",
]

exclude = [
    "archive"
]

