[package]
name = "alds"
version = "0.1.0"
edition = "2021"

[dependencies]
# original crates
mod_int = { path = "crates/mod_int" }
union_find = { path = "crates/union_find" }
seg_lib = { path = "crates/seg_lib" }

# third-party crates
rustc-hash = "2.1.1"

[dev-dependencies]
proconio = { version = "0.5.0", features = ["derive"] }

[workspace]
members = [
    "crates/mod_int",
    "crates/seg_lib",
    "crates/union_find",
]

exclude = [
    "/archive",
    "/target"
]

