[package]
name = "alds"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace.dependencies]
proconio = { version = "0.5.0", features = ["derive"] }

[workspace]
members = [
    "crates/mod_int",
    "crates/seg_lib",
    "crates/sparse_table",
    "crates/union_find",
]

exclude = [
    "/archive",
    "/target"
]
