[package]
name = "alds"
version = "0.1.0"
edition = "2021"

[dependencies]
# original crates
mod_int = { path = "crates/mod_int" }
union_find = { path = "crates/union_find" }
segment_tree = { path = "crates/segment_tree" }

# third-party crates
proconio = { version = "0.5.0", features = ["derive"] }
rustc-hash = "2.1.1"


[workspace]
members = [
    "crates/mod_int",
    "crates/segment_tree",
    "crates/union_find",
]

exclude = [
    "archive"
]

