[book]
authors = ["qdot3"]
language = "ja"
multilingual = false
src = "src"
title = "alds book"

[output.html]
default-theme = "rust"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
